## Thyroid Disease Prediction

### Model Building

In [2]:
## Importing important library

import numpy as nu 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics  import roc_auc_score,accuracy_score
from sklearn.neighbors import KNeighborsClassifier

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
#from kneed import KneeLocator


In [3]:
## import logging
import logging
logging.basicConfig(filename="Model Training.log", level=logging.INFO, format='%(asctime)s %(message)s',
					datefmt="%Y-%m-%d %H:%M:%S")



In [4]:
## Input data
x_sampled = pd.read_csv('data/x_sampled.csv')
x_sampled.head()

Age  Sex  On Thyroxine  Query on Thyroxine  On Antithyroid Medication  \
0  42.0  0.0           0.0                 0.0                        0.0   
1  24.0  0.0           0.0                 0.0                        0.0   
2  47.0  1.0           0.0                 0.0                        0.0   
3  71.0  0.0           1.0                 0.0                        0.0   
4  71.0  0.0           0.0                 0.0                        0.0   

   Sick  Pregnant  Thyroid Surgery  I131 Treatment  Query Hypothyroid  \
0   0.0       0.0              0.0             0.0                0.0   
1   0.0       0.0              0.0             0.0                0.0   
2   0.0       0.0              0.0             0.0                0.0   
3   0.0       0.0              0.0             0.0                0.0   
4   0.0       0.0              0.0             0.0                0.0   

   Query Hyperthyroid  Lithium  Goitre  Tumor  Hypopituitary  Psych   T3  \
0                 0.0      0.0     0.0    0.0            0.0    0.0  3.0   
1                 0.0      0.0     0.0    0.0            0.0    0.0  3.0   
2                 0.0      0.0     0.0    0.0            0.0    0.0  3.0   
3                 0.0      0.0     0.0    0.0            0.0    0.0  3.0   
4                 0.0      0.0     0.0    0.0            0.0    0.0  2.0   

     TT4  T4U    FTI  
0  126.0  2.0  110.0  
1  103.0  2.0   97.0  
2  110.0  2.0  121.0  
3  176.0  2.0  178.0  
4   62.0  2.0   71.0

In [5]:
## Output data
y_sampled = pd.read_csv('data/y_sampled.csv')
y_sampled.head()

Category
0       2.0
1       2.0
2       2.0
3       2.0
4       2.0

##### There are lots of feature in our dataset so using feature engineering I select only 10 most important features to model building.

In [6]:
logging.info(" ##### There are lots of feature in our dataset so using feature engineering I select only 10 most important features to model building....")

In [7]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel

In [8]:
x_sampled.columns

Index(['Age', 'Sex', 'On Thyroxine', 'Query on Thyroxine',
       'On Antithyroid Medication', 'Sick', 'Pregnant', 'Thyroid Surgery',
       'I131 Treatment', 'Query Hypothyroid', 'Query Hyperthyroid', 'Lithium',
       'Goitre', 'Tumor', 'Hypopituitary', 'Psych', 'T3', 'TT4', 'T4U', 'FTI'],
      dtype='object')

In [9]:
x_sampled=x_sampled.drop(['Query Hypothyroid'], axis = 1)
x_sampled=x_sampled.drop(['Query Hyperthyroid'], axis = 1)
x_sampled=x_sampled.drop('Psych', axis = 1)
x_sampled=x_sampled.drop(['On Thyroxine','On Antithyroid Medication','Hypopituitary'], axis = 1)





In [10]:
print(len(x_sampled), len(y_sampled))


11012 11012


In [11]:
# Split the data into training and testing sets
X2_train, X2_test, y2_train, y2_test = train_test_split(x_sampled, y_sampled, test_size=0.2, random_state=42)


In [12]:
# Use a RandomForestClassifier for feature selection
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X2_train, y2_train)


c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=42)

In [13]:
# Get feature importances
feature_importances = clf.feature_importances_

In [14]:
#Create a DataFrame to better visualize the importances
feature_importance_df = pd.DataFrame({'Feature': x_sampled.columns, 'Importance': feature_importances})


In [15]:
# Sort features by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)


In [16]:
# Select the top 10 features
top_features = feature_importance_df.head(10)['Feature'].tolist()


In [17]:
# Display the top 10 features
logging.info('Displa the top 10 important features')
print("Top 10 Features:")
print(top_features)

Top 10 Features:
['FTI', 'TT4', 'T3', 'Age', 'Sex', 'Tumor', 'Pregnant', 'Sick', 'T4U', 'I131 Treatment']


In [18]:
# Select only the top 10 features for further analysis
X_train_selected = X2_train[top_features]
X_test_selected = X2_test[top_features]

In [19]:
X_train_selected

FTI    TT4   T3   Age  Sex  Tumor  Pregnant  Sick  T4U  \
2025   139.0  102.0  2.0  90.0  1.0    0.0       0.0   0.0  2.0   
594    159.0  177.0  3.0  70.0  0.0    1.0       0.0   0.0  2.0   
1558   161.0  129.0  2.0  55.0  0.0    0.0       0.0   0.0  2.0   
9426   140.0   79.0  1.0  76.0  1.0    0.0       0.0   0.0  2.0   
10119  114.0   87.0  2.0  84.0  0.0    0.0       0.0   0.0  2.0   
...      ...    ...  ...   ...  ...    ...       ...   ...  ...   
5734   218.0  199.0  4.0  73.0  0.0    0.0       0.0   0.0  2.0   
5191   201.0  201.0  4.0  52.0  0.0    0.0       0.0   0.0  2.0   
5390   206.0  157.0  5.0  47.0  1.0    0.0       0.0   0.0  2.0   
860    143.0  102.0  2.0  69.0  1.0    0.0       0.0   1.0  2.0   
7270    20.0   22.0  2.0  26.0  0.0    0.0       0.0   0.0  2.0   

       I131 Treatment  
2025              0.0  
594               0.0  
1558              0.0  
9426              0.0  
10119             0.0  
...               ...  
5734              0.0  
5191              0.0  
5390              0.0  
860               0.0  
7270              0.0  

[8809 rows x 10 columns]

In [20]:
X_test_selected

FTI    TT4   T3   Age  Sex  Tumor  Pregnant  Sick  T4U  \
4043   201.0  201.0  4.0  52.0  0.0    0.0       0.0   0.0  2.0   
5250   248.0  251.0  5.0  54.0  0.0    0.0       0.0   0.0  2.0   
3694   218.0  199.0  4.0  73.0  0.0    0.0       0.0   0.0  2.0   
6004    94.0  105.0  3.0  27.0  0.0    0.0       0.0   0.0  2.0   
10981   18.0   20.0  3.0  53.0  0.0    0.0       0.0   0.0  2.0   
...      ...    ...  ...   ...  ...    ...       ...   ...  ...   
5170   313.0  251.0  7.0  16.0  0.0    0.0       0.0   0.0  2.0   
7189    75.0   69.0  3.0   2.0  1.0    0.0       0.0   0.0  2.0   
1419   109.0   91.0  3.0  29.0  0.0    0.0       0.0   0.0  2.0   
2392   106.0  110.0  3.0  42.0  0.0    0.0       0.0   0.0  2.0   
2748   149.0  156.0  3.0  71.0  1.0    0.0       0.0   0.0  2.0   

       I131 Treatment  
4043              0.0  
5250              0.0  
3694              0.0  
6004              0.0  
10981             0.0  
...               ...  
5170              0.0  
7189              0.0  
1419              0.0  
2392              0.0  
2748              0.0  

[2203 rows x 10 columns]

In [21]:
y2_train

Category
2025        2.0
594         2.0
1558        2.0
9426        3.0
10119       3.0
...         ...
5734        0.0
5191        0.0
5390        0.0
860         2.0
7270        1.0

[8809 rows x 1 columns]

In [22]:
y2_test

Category
4043        0.0
5250        0.0
3694        0.0
6004        1.0
10981       3.0
...         ...
5170        0.0
7189        1.0
1419        2.0
2392        2.0
2748        2.0

[2203 rows x 1 columns]

### Fitting data in various models

In [23]:
## import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import pickle
from sklearn.utils import resample

In [24]:
## SVM classifier
logging.info('Importing data in svm_classifier model')
def svm_classifier(X_train_selected,X_test_selected,y2_train,y2_test):
    classifier_svm=SVC(kernel='rbf',random_state=0)
    classifier_svm.fit(X_train_selected,y2_train)
    y_pred=classifier_svm.predict(X_test_selected)
    cm=confusion_matrix(y2_test,y_pred)
    return (f'Train Score:{classifier_svm.score(X_train_selected,y2_train)}\n Test Score:{classifier_svm.score(X_test_selected,y2_test)}')

In [25]:
## KNN classifier model
logging.info('Import data in KNN_classifier model')
def knn_classifier(X_train_selected,X_test_selected,y2_train,y2_test):
    classifier_knn=KNeighborsClassifier(metric='minkowski',p=2)
    classifier_knn.fit(X_train_selected,y2_train)
    y_pred=classifier_knn.predict(X_test_selected)
    cm=confusion_matrix(y2_test,y_pred)
    return (f'Train Score:{classifier_knn.score(X_train_selected,y2_train)}\n Test Score:{classifier_knn.score(X_test_selected,y2_test)}')

In [26]:
## DecisionTree classifier model
logging.info('import data in Decision Tree classifier model')
def tree_classifier(X_train_selected,X_test_selected,y2_train,y2_test):
    classifier_tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
    classifier_tree.fit(X_train_selected,y2_train)
    y_pred=classifier_tree.predict(X_test_selected)
    cm=confusion_matrix(y2_test,y_pred)
    return (f'Train Score:{classifier_tree.score(X_train_selected,y2_train)}\n Test Score:{classifier_tree.score(X_test_selected,y2_test)}')

In [27]:
## RandomForest classifier model
logging.info('Import data in RandomForest classifer model')
def forest_classifier(X_train_selected,X_test_selected,y2_train,y2_test):
    classifier_forest=RandomForestClassifier(criterion='entropy',random_state=0)
    classifier_forest.fit(X_train_selected,y2_train)
    y_pred=classifier_forest.predict(X_test_selected)
    cm=confusion_matrix(y2_test,y_pred)
    
    return (f'Train Score:{classifier_forest.score(X_train_selected,y2_train)}\n Test Score:{classifier_forest.score(X_test_selected,y2_test)}')
    

In [28]:
logging.info('Now print the score of each and every model')
def print_score(X_train_selected, X_test_selected, y2_train, y2_test):
    print("SVM:\n")
    result1=svm_classifier(X_train_selected, X_test_selected, y2_train, y2_test)
    print(result1)
    print("-"*100)
    print()

    print("KNN:\n")
    result2=knn_classifier(X_train_selected, X_test_selected, y2_train, y2_test)
    print(result2)

    print("-"*100)
    print()

    print("Decision Tree:\n")
    result4=tree_classifier(X_train_selected, X_test_selected, y2_train, y2_test)
    print(result4)

    print("-"*100)
    print()

    print("Random Forest:\n")
    result5=forest_classifier(X_train_selected, X_test_selected, y2_train, y2_test)
    print(result5)

In [29]:
print_score(X_train_selected, X_test_selected, y2_train, y2_test)

SVM:



c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Train Score:0.6205017595640822
 Test Score:0.6295960054471176
----------------------------------------------------------------------------------------------------

KNN:



c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Train Score:0.8636621636962197
 Test Score:0.8443032228778938
----------------------------------------------------------------------------------------------------

Decision Tree:

Train Score:0.9119082756271994
 Test Score:0.8887880163413527
----------------------------------------------------------------------------------------------------

Random Forest:



c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Train Score:0.9119082756271994
 Test Score:0.8951429868361326


In [30]:
##Performance Metrics
## Performance Metrics
classifier_forest = RandomForestClassifier(criterion = 'entropy')
classifier_forest.fit(X_train_selected,y2_train)
y_pred = classifier_forest.predict(X_test_selected)
cm = confusion_matrix(y2_test,y_pred)
cm

c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


array([[557,   0,   0,   0],
       [  0, 494,   0,  50],
       [ 27,  54, 431,  39],
       [ 38,  25,   0, 488]], dtype=int64)

In [31]:
## Classification Report (Accuracy, Precision, Recall and F1 Score)
from sklearn.metrics import roc_auc_score,roc_curve,classification_report

In [32]:
print(classification_report(y2_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.90      1.00      0.94       557
         1.0       0.86      0.91      0.88       544
         2.0       1.00      0.78      0.88       551
         3.0       0.85      0.89      0.87       551

    accuracy                           0.89      2203
   macro avg       0.90      0.89      0.89      2203
weighted avg       0.90      0.89      0.89      2203



### Hyperparameter Tunning

In [33]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score (estimator = classifier_forest, X=X_train_selected,y=y2_train,cv=10)
print(accuracies.mean())

c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
c:\Users\nk141\anaconda3\Lib\site-packages\sklearn\base.py:1351: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for

0.890113249406666


In [34]:
import pickle
filename = 'thyroid_model.pkl'
pickle.dump(classifier_forest,open(filename,'wb'))

In [35]:
model = open('thyroid_model.pkl','rb')
forest = pickle.load(model)

In [36]:
y_pred = forest.predict(X_test_selected)

In [37]:
confusion_matrix(y2_test, y_pred)

array([[557,   0,   0,   0],
       [  0, 494,   0,  50],
       [ 27,  54, 431,  39],
       [ 38,  25,   0, 488]], dtype=int64)

#### Output of our model prediction is as:
(1) SVM is 0.61
(2) KNN is 0.83
(3) Decision Tree is 0.88
(4) Random Forest is 0.90

In [38]:
logging.info('Model higest accuracy is 90 percent with Random Forest')

In [39]:
##Savinf model
logging.info('Saving Random forest_model')
import os
import pickle
file = open('classifier_forest.pkl','wb')
pickle.dump(forest_classifier, file)
file.close()

In [40]:
logging.info('Saving Decision_Tree_model')
import os
import pickle
file = open('tree_classifier.pkl','wb')
pickle.dump(tree_classifier, file)
file.close()

### Model Building using Logistic Regresson 

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

# Your code here

# Create and train the logistic regression model
model = LogisticRegression(random_state=42)
model.fit(X_train_selected, y2_train)



LogisticRegression(random_state=42)

In [43]:
# Make predictions on the test set
y_pred = model.predict(X_test_selected)


In [44]:
y_pred

array([0., 0., 0., ..., 2., 2., 3.])

In [45]:
# Evaluate the model
accuracy = accuracy_score(y2_test, y_pred)
conf_matrix = confusion_matrix(y2_test, y_pred)
classification_rep = classification_report(y2_test, y_pred)

In [46]:
## Now see the accuracy of the model
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_rep)

Accuracy: 0.6645483431684067
Confusion Matrix:
 [[451  22  13  71]
 [ 17 317 127  83]
 [ 60 111 301  79]
 [ 25 101  30 395]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.82      0.81      0.81       557
         1.0       0.58      0.58      0.58       544
         2.0       0.64      0.55      0.59       551
         3.0       0.63      0.72      0.67       551

    accuracy                           0.66      2203
   macro avg       0.66      0.66      0.66      2203
weighted avg       0.67      0.66      0.66      2203



In [47]:
import os
import pickle
file = open('modelLogisticReg.pkl','wb')
pickle.dump(model, file)
file.close()

